language: node_js

node_js:
  - "10.15.3"

before_script:
  - npm i

script:
  - npm run example:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
